<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Mading;
use App\Models\User;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // \App\Models\User::factory(10)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

        // Mading::create([
        //     'judul' => 'Futsal',
        //     'excerpt' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium temporibus voluptatibus sequi eius expedita, facere laborum alias aspernatur. Consectetur explicabo temporibus molestiae incidunt, similique eaque facilis. Saepe totam atque consectetur.',
        //     'category' => 'Sepak Bola',
        //     'body' => '<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui, cum atque. Incidunt et reprehenderit voluptatem necessitatibus tempore, nostrum aliquam accusantium inventore tenetur ab atque dignissimos labore, harum earum placeat quia omnis est magnam, molestiae cum beatae laudantium. Harum esse unde a dolore voluptates officiis amet maxime alias doloremque sunt est voluptatum optio numquam vero nisi corrupti ducimus beatae illum ratione, rem velit totam iste temporibus! Esse ut rem incidunt nobis commodi nesciunt assumenda officiis distinctio alias excepturi repellendus, quod laboriosam iusto quas in hic ex eos eligendi blanditiis, repudiandae odio tenetur. Iste explicabo nulla aliquid numquam dolor, eum voluptas corrupti eaque, ipsum eos provident repellat quibusdam ratione laborum pariatur totam qui quisquam hic officiis eveniet, voluptates neque adipisci architecto magnam. Libero, numquam. Dolore facilis commodi est autem natus, consequatur beatae debitis eum, in placeat numquam, cumque aperiam? Eius soluta nostrum voluptatibus, non illo quis maiores mollitia sed ipsam, porro consequuntur.</p>
        //     <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Deserunt, et velit. Quae et natus ducimus. Adipisci delectus quisquam aspernatur temporibus a dolorem iure aut explicabo laborum! Ab minus deleniti recusandae eos temporibus. Aspernatur minima eaque maxime molestiae laborum hic, quasi quos atque magnam facilis? Totam nam soluta labore illo voluptas similique dolorem optio ea exercitationem praesentium deserunt, omnis rem animi dignissimos ut reiciendis et! Alias repellendus sunt, velit, expedita hic magnam cupiditate, minima facilis impedit similique ipsum fugit dolorum maxime perferendis molestias obcaecati quis officiis. Iste, necessitatibus deserunt blanditiis consequatur mollitia aliquid ratione nobis eaque porro est totam illum vero voluptatem autem impedit amet ab iusto minus expedita quos. Amet a esse tempore nisi modi quisquam eos qui ullam in id ab quidem minus voluptatibus placeat ipsum nostrum vel atque asperiores recusandae reiciendis eligendi, autem dolore iusto molestias. Consequuntur, quaerat! Quam eveniet, nulla perferendis fuga est mollitia quis provident cumque officiis fugit quas hic quos eaque repellat magnam facere sed eligendi nisi dolorem laboriosam ab qui veritatis aut! Nesciunt voluptatem commodi quibusdam unde deleniti, itaque velit, voluptates quasi nostrum odit quos sit, maiores alias nulla tempore consequuntur. Ipsam corporis libero, odit in reprehenderit distinctio perspiciatis architecto, fugiat, debitis voluptatem impedit.</p>
        //     <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur similique, adipisci repellat vitae aliquam libero atque soluta iste qui perspiciatis magnam earum ratione alias sed voluptatibus ad animi sint fugiat consequuntur iusto eos eaque quae. Nihil neque, recusandae magnam ut ratione quia voluptate. Deleniti, error numquam. Sed, alias. Sunt hic magnam, delectus vero placeat voluptas quidem culpa mollitia suscipit quis odit ullam, reprehenderit harum labore! Maiores nihil dolorem iusto, doloribus, voluptatum nostrum eum ratione asperiores molestiae minus minima perspiciatis natus. Reprehenderit consequuntur officiis quas voluptate voluptatibus? Sunt unde vel dolorum dolor commodi eveniet! Dolorum exercitationem eligendi odit earum, cumque, voluptatibus magni repudiandae quidem ab ad velit, doloribus saepe ex deserunt assumenda vitae dolores eaque illo quasi tenetur porro veniam temporibus! Ea nostrum, nobis cupiditate, quam sunt ullam quod facere nisi magni porro autem eum nam? Illo magni quia recusandae numquam quasi amet ea, cum asperiores voluptatem repellendus libero, blanditiis quis! Provident iusto accusamus quo fugit nisi, corrupti suscipit omnis, assumenda consequatur magnam ipsum odio obcaecati soluta corporis laborum mollitia quod vel libero asperiores deleniti autem voluptas doloremque beatae numquam. Voluptates facere dolor iste quo ipsam. Temporibus ad, iure, nulla cumque repudiandae sed magni iusto porro consequatur eveniet saepe quod dolorem culpa dolorum corporis ratione voluptatibus reprehenderit ea obcaecati consectetur deleniti enim sunt hic laborum! Eos architecto quia ut beatae nostrum totam, porro soluta ipsum omnis amet assumenda alias aspernatur. Aut eos ullam velit! Rem repellendus labore praesentium itaque incidunt eum repellat sit. Obcaecati ea recusandae blanditiis porro harum ipsa? Corporis recusandae repellendus repudiandae quaerat saepe obcaecati error aut, animi assumenda, in eius. Aliquid quam praesentium a inventore alias quod vel dicta nam officiis, enim quos accusamus hic harum accusantium deleniti, ab veniam ea dolore obcaecati aut odio eius. Harum, corrupti tempore! Atque, voluptatibus suscipit aut ut quisquam dignissimos ad vitae!</p>',
        //     'user_id' => 1,
        // ]);
        // Mading::create([
        //     'judul' => 'Volly Ball',
        //     'excerpt' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium temporibus voluptatibus sequi eius expedita, facere laborum alias aspernatur. Consectetur explicabo temporibus molestiae incidunt, similique eaque facilis. Saepe totam atque consectetur.',
        //     'category' => 'Vollyball',
        //     'body' => '<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui, cum atque. Incidunt et reprehenderit voluptatem necessitatibus tempore, nostrum aliquam accusantium inventore tenetur ab atque dignissimos labore, harum earum placeat quia omnis est magnam, molestiae cum beatae laudantium. Harum esse unde a dolore voluptates officiis amet maxime alias doloremque sunt est voluptatum optio numquam vero nisi corrupti ducimus beatae illum ratione, rem velit totam iste temporibus! Esse ut rem incidunt nobis commodi nesciunt assumenda officiis distinctio alias excepturi repellendus, quod laboriosam iusto quas in hic ex eos eligendi blanditiis, repudiandae odio tenetur. Iste explicabo nulla aliquid numquam dolor, eum voluptas corrupti eaque, ipsum eos provident repellat quibusdam ratione laborum pariatur totam qui quisquam hic officiis eveniet, voluptates neque adipisci architecto magnam. Libero, numquam. Dolore facilis commodi est autem natus, consequatur beatae debitis eum, in placeat numquam, cumque aperiam? Eius soluta nostrum voluptatibus, non illo quis maiores mollitia sed ipsam, porro consequuntur.</p>
        //     <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Deserunt, et velit. Quae et natus ducimus. Adipisci delectus quisquam aspernatur temporibus a dolorem iure aut explicabo laborum! Ab minus deleniti recusandae eos temporibus. Aspernatur minima eaque maxime molestiae laborum hic, quasi quos atque magnam facilis? Totam nam soluta labore illo voluptas similique dolorem optio ea exercitationem praesentium deserunt, omnis rem animi dignissimos ut reiciendis et! Alias repellendus sunt, velit, expedita hic magnam cupiditate, minima facilis impedit similique ipsum fugit dolorum maxime perferendis molestias obcaecati quis officiis. Iste, necessitatibus deserunt blanditiis consequatur mollitia aliquid ratione nobis eaque porro est totam illum vero voluptatem autem impedit amet ab iusto minus expedita quos. Amet a esse tempore nisi modi quisquam eos qui ullam in id ab quidem minus voluptatibus placeat ipsum nostrum vel atque asperiores recusandae reiciendis eligendi, autem dolore iusto molestias. Consequuntur, quaerat! Quam eveniet, nulla perferendis fuga est mollitia quis provident cumque officiis fugit quas hic quos eaque repellat magnam facere sed eligendi nisi dolorem laboriosam ab qui veritatis aut! Nesciunt voluptatem commodi quibusdam unde deleniti, itaque velit, voluptates quasi nostrum odit quos sit, maiores alias nulla tempore consequuntur. Ipsam corporis libero, odit in reprehenderit distinctio perspiciatis architecto, fugiat, debitis voluptatem impedit.</p>
        //     <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur similique, adipisci repellat vitae aliquam libero atque soluta iste qui perspiciatis magnam earum ratione alias sed voluptatibus ad animi sint fugiat consequuntur iusto eos eaque quae. Nihil neque, recusandae magnam ut ratione quia voluptate. Deleniti, error numquam. Sed, alias. Sunt hic magnam, delectus vero placeat voluptas quidem culpa mollitia suscipit quis odit ullam, reprehenderit harum labore! Maiores nihil dolorem iusto, doloribus, voluptatum nostrum eum ratione asperiores molestiae minus minima perspiciatis natus. Reprehenderit consequuntur officiis quas voluptate voluptatibus? Sunt unde vel dolorum dolor commodi eveniet! Dolorum exercitationem eligendi odit earum, cumque, voluptatibus magni repudiandae quidem ab ad velit, doloribus saepe ex deserunt assumenda vitae dolores eaque illo quasi tenetur porro veniam temporibus! Ea nostrum, nobis cupiditate, quam sunt ullam quod facere nisi magni porro autem eum nam? Illo magni quia recusandae numquam quasi amet ea, cum asperiores voluptatem repellendus libero, blanditiis quis! Provident iusto accusamus quo fugit nisi, corrupti suscipit omnis, assumenda consequatur magnam ipsum odio obcaecati soluta corporis laborum mollitia quod vel libero asperiores deleniti autem voluptas doloremque beatae numquam. Voluptates facere dolor iste quo ipsam. Temporibus ad, iure, nulla cumque repudiandae sed magni iusto porro consequatur eveniet saepe quod dolorem culpa dolorum corporis ratione voluptatibus reprehenderit ea obcaecati consectetur deleniti enim sunt hic laborum! Eos architecto quia ut beatae nostrum totam, porro soluta ipsum omnis amet assumenda alias aspernatur. Aut eos ullam velit! Rem repellendus labore praesentium itaque incidunt eum repellat sit. Obcaecati ea recusandae blanditiis porro harum ipsa? Corporis recusandae repellendus repudiandae quaerat saepe obcaecati error aut, animi assumenda, in eius. Aliquid quam praesentium a inventore alias quod vel dicta nam officiis, enim quos accusamus hic harum accusantium deleniti, ab veniam ea dolore obcaecati aut odio eius. Harum, corrupti tempore! Atque, voluptatibus suscipit aut ut quisquam dignissimos ad vitae!</p>',
        //     'user_id' => 1,
        // ]);
        // Mading::create([
        //     'judul' => 'Pramuka',
        //     'excerpt' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium temporibus voluptatibus sequi eius expedita, facere laborum alias aspernatur. Consectetur explicabo temporibus molestiae incidunt, similique eaque facilis. Saepe totam atque consectetur.',
        //     'category' => 'Pramuka',
        //     'body' => '<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui, cum atque. Incidunt et reprehenderit voluptatem necessitatibus tempore, nostrum aliquam accusantium inventore tenetur ab atque dignissimos labore, harum earum placeat quia omnis est magnam, molestiae cum beatae laudantium. Harum esse unde a dolore voluptates officiis amet maxime alias doloremque sunt est voluptatum optio numquam vero nisi corrupti ducimus beatae illum ratione, rem velit totam iste temporibus! Esse ut rem incidunt nobis commodi nesciunt assumenda officiis distinctio alias excepturi repellendus, quod laboriosam iusto quas in hic ex eos eligendi blanditiis, repudiandae odio tenetur. Iste explicabo nulla aliquid numquam dolor, eum voluptas corrupti eaque, ipsum eos provident repellat quibusdam ratione laborum pariatur totam qui quisquam hic officiis eveniet, voluptates neque adipisci architecto magnam. Libero, numquam. Dolore facilis commodi est autem natus, consequatur beatae debitis eum, in placeat numquam, cumque aperiam? Eius soluta nostrum voluptatibus, non illo quis maiores mollitia sed ipsam, porro consequuntur.</p>
        //     <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Deserunt, et velit. Quae et natus ducimus. Adipisci delectus quisquam aspernatur temporibus a dolorem iure aut explicabo laborum! Ab minus deleniti recusandae eos temporibus. Aspernatur minima eaque maxime molestiae laborum hic, quasi quos atque magnam facilis? Totam nam soluta labore illo voluptas similique dolorem optio ea exercitationem praesentium deserunt, omnis rem animi dignissimos ut reiciendis et! Alias repellendus sunt, velit, expedita hic magnam cupiditate, minima facilis impedit similique ipsum fugit dolorum maxime perferendis molestias obcaecati quis officiis. Iste, necessitatibus deserunt blanditiis consequatur mollitia aliquid ratione nobis eaque porro est totam illum vero voluptatem autem impedit amet ab iusto minus expedita quos. Amet a esse tempore nisi modi quisquam eos qui ullam in id ab quidem minus voluptatibus placeat ipsum nostrum vel atque asperiores recusandae reiciendis eligendi, autem dolore iusto molestias. Consequuntur, quaerat! Quam eveniet, nulla perferendis fuga est mollitia quis provident cumque officiis fugit quas hic quos eaque repellat magnam facere sed eligendi nisi dolorem laboriosam ab qui veritatis aut! Nesciunt voluptatem commodi quibusdam unde deleniti, itaque velit, voluptates quasi nostrum odit quos sit, maiores alias nulla tempore consequuntur. Ipsam corporis libero, odit in reprehenderit distinctio perspiciatis architecto, fugiat, debitis voluptatem impedit.</p>
        //     <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur similique, adipisci repellat vitae aliquam libero atque soluta iste qui perspiciatis magnam earum ratione alias sed voluptatibus ad animi sint fugiat consequuntur iusto eos eaque quae. Nihil neque, recusandae magnam ut ratione quia voluptate. Deleniti, error numquam. Sed, alias. Sunt hic magnam, delectus vero placeat voluptas quidem culpa mollitia suscipit quis odit ullam, reprehenderit harum labore! Maiores nihil dolorem iusto, doloribus, voluptatum nostrum eum ratione asperiores molestiae minus minima perspiciatis natus. Reprehenderit consequuntur officiis quas voluptate voluptatibus? Sunt unde vel dolorum dolor commodi eveniet! Dolorum exercitationem eligendi odit earum, cumque, voluptatibus magni repudiandae quidem ab ad velit, doloribus saepe ex deserunt assumenda vitae dolores eaque illo quasi tenetur porro veniam temporibus! Ea nostrum, nobis cupiditate, quam sunt ullam quod facere nisi magni porro autem eum nam? Illo magni quia recusandae numquam quasi amet ea, cum asperiores voluptatem repellendus libero, blanditiis quis! Provident iusto accusamus quo fugit nisi, corrupti suscipit omnis, assumenda consequatur magnam ipsum odio obcaecati soluta corporis laborum mollitia quod vel libero asperiores deleniti autem voluptas doloremque beatae numquam. Voluptates facere dolor iste quo ipsam. Temporibus ad, iure, nulla cumque repudiandae sed magni iusto porro consequatur eveniet saepe quod dolorem culpa dolorum corporis ratione voluptatibus reprehenderit ea obcaecati consectetur deleniti enim sunt hic laborum! Eos architecto quia ut beatae nostrum totam, porro soluta ipsum omnis amet assumenda alias aspernatur. Aut eos ullam velit! Rem repellendus labore praesentium itaque incidunt eum repellat sit. Obcaecati ea recusandae blanditiis porro harum ipsa? Corporis recusandae repellendus repudiandae quaerat saepe obcaecati error aut, animi assumenda, in eius. Aliquid quam praesentium a inventore alias quod vel dicta nam officiis, enim quos accusamus hic harum accusantium deleniti, ab veniam ea dolore obcaecati aut odio eius. Harum, corrupti tempore! Atque, voluptatibus suscipit aut ut quisquam dignissimos ad vitae!</p>',
        //     'user_id' => 1,
        // ]);
        // Mading::create([
        //     'judul' => 'Rekayasa Perangkat Lunak',
        //     'excerpt' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium temporibus voluptatibus sequi eius expedita, facere laborum alias aspernatur. Consectetur explicabo temporibus molestiae incidunt, similique eaque facilis. Saepe totam atque consectetur.',
        //     'category' => 'Sofware Engineering',
        //     'body' => '<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui, cum atque. Incidunt et reprehenderit voluptatem necessitatibus tempore, nostrum aliquam accusantium inventore tenetur ab atque dignissimos labore, harum earum placeat quia omnis est magnam, molestiae cum beatae laudantium. Harum esse unde a dolore voluptates officiis amet maxime alias doloremque sunt est voluptatum optio numquam vero nisi corrupti ducimus beatae illum ratione, rem velit totam iste temporibus! Esse ut rem incidunt nobis commodi nesciunt assumenda officiis distinctio alias excepturi repellendus, quod laboriosam iusto quas in hic ex eos eligendi blanditiis, repudiandae odio tenetur. Iste explicabo nulla aliquid numquam dolor, eum voluptas corrupti eaque, ipsum eos provident repellat quibusdam ratione laborum pariatur totam qui quisquam hic officiis eveniet, voluptates neque adipisci architecto magnam. Libero, numquam. Dolore facilis commodi est autem natus, consequatur beatae debitis eum, in placeat numquam, cumque aperiam? Eius soluta nostrum voluptatibus, non illo quis maiores mollitia sed ipsam, porro consequuntur.</p>
        //     <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Deserunt, et velit. Quae et natus ducimus. Adipisci delectus quisquam aspernatur temporibus a dolorem iure aut explicabo laborum! Ab minus deleniti recusandae eos temporibus. Aspernatur minima eaque maxime molestiae laborum hic, quasi quos atque magnam facilis? Totam nam soluta labore illo voluptas similique dolorem optio ea exercitationem praesentium deserunt, omnis rem animi dignissimos ut reiciendis et! Alias repellendus sunt, velit, expedita hic magnam cupiditate, minima facilis impedit similique ipsum fugit dolorum maxime perferendis molestias obcaecati quis officiis. Iste, necessitatibus deserunt blanditiis consequatur mollitia aliquid ratione nobis eaque porro est totam illum vero voluptatem autem impedit amet ab iusto minus expedita quos. Amet a esse tempore nisi modi quisquam eos qui ullam in id ab quidem minus voluptatibus placeat ipsum nostrum vel atque asperiores recusandae reiciendis eligendi, autem dolore iusto molestias. Consequuntur, quaerat! Quam eveniet, nulla perferendis fuga est mollitia quis provident cumque officiis fugit quas hic quos eaque repellat magnam facere sed eligendi nisi dolorem laboriosam ab qui veritatis aut! Nesciunt voluptatem commodi quibusdam unde deleniti, itaque velit, voluptates quasi nostrum odit quos sit, maiores alias nulla tempore consequuntur. Ipsam corporis libero, odit in reprehenderit distinctio perspiciatis architecto, fugiat, debitis voluptatem impedit.</p>
        //     <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur similique, adipisci repellat vitae aliquam libero atque soluta iste qui perspiciatis magnam earum ratione alias sed voluptatibus ad animi sint fugiat consequuntur iusto eos eaque quae. Nihil neque, recusandae magnam ut ratione quia voluptate. Deleniti, error numquam. Sed, alias. Sunt hic magnam, delectus vero placeat voluptas quidem culpa mollitia suscipit quis odit ullam, reprehenderit harum labore! Maiores nihil dolorem iusto, doloribus, voluptatum nostrum eum ratione asperiores molestiae minus minima perspiciatis natus. Reprehenderit consequuntur officiis quas voluptate voluptatibus? Sunt unde vel dolorum dolor commodi eveniet! Dolorum exercitationem eligendi odit earum, cumque, voluptatibus magni repudiandae quidem ab ad velit, doloribus saepe ex deserunt assumenda vitae dolores eaque illo quasi tenetur porro veniam temporibus! Ea nostrum, nobis cupiditate, quam sunt ullam quod facere nisi magni porro autem eum nam? Illo magni quia recusandae numquam quasi amet ea, cum asperiores voluptatem repellendus libero, blanditiis quis! Provident iusto accusamus quo fugit nisi, corrupti suscipit omnis, assumenda consequatur magnam ipsum odio obcaecati soluta corporis laborum mollitia quod vel libero asperiores deleniti autem voluptas doloremque beatae numquam. Voluptates facere dolor iste quo ipsam. Temporibus ad, iure, nulla cumque repudiandae sed magni iusto porro consequatur eveniet saepe quod dolorem culpa dolorum corporis ratione voluptatibus reprehenderit ea obcaecati consectetur deleniti enim sunt hic laborum! Eos architecto quia ut beatae nostrum totam, porro soluta ipsum omnis amet assumenda alias aspernatur. Aut eos ullam velit! Rem repellendus labore praesentium itaque incidunt eum repellat sit. Obcaecati ea recusandae blanditiis porro harum ipsa? Corporis recusandae repellendus repudiandae quaerat saepe obcaecati error aut, animi assumenda, in eius. Aliquid quam praesentium a inventore alias quod vel dicta nam officiis, enim quos accusamus hic harum accusantium deleniti, ab veniam ea dolore obcaecati aut odio eius. Harum, corrupti tempore! Atque, voluptatibus suscipit aut ut quisquam dignissimos ad vitae!</p>',
        //     'user_id' => 1,
        // ]);
        // Mading::create([
        //     'judul' => 'Perbankan Syariah',
        //     'excerpt' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium temporibus voluptatibus sequi eius expedita, facere laborum alias aspernatur. Consectetur explicabo temporibus molestiae incidunt, similique eaque facilis. Saepe totam atque consectetur.',
        //     'category' => 'Bank Syariah',
        //     'body' => '<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui, cum atque. Incidunt et reprehenderit voluptatem necessitatibus tempore, nostrum aliquam accusantium inventore tenetur ab atque dignissimos labore, harum earum placeat quia omnis est magnam, molestiae cum beatae laudantium. Harum esse unde a dolore voluptates officiis amet maxime alias doloremque sunt est voluptatum optio numquam vero nisi corrupti ducimus beatae illum ratione, rem velit totam iste temporibus! Esse ut rem incidunt nobis commodi nesciunt assumenda officiis distinctio alias excepturi repellendus, quod laboriosam iusto quas in hic ex eos eligendi blanditiis, repudiandae odio tenetur. Iste explicabo nulla aliquid numquam dolor, eum voluptas corrupti eaque, ipsum eos provident repellat quibusdam ratione laborum pariatur totam qui quisquam hic officiis eveniet, voluptates neque adipisci architecto magnam. Libero, numquam. Dolore facilis commodi est autem natus, consequatur beatae debitis eum, in placeat numquam, cumque aperiam? Eius soluta nostrum voluptatibus, non illo quis maiores mollitia sed ipsam, porro consequuntur.</p>
        //     <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Deserunt, et velit. Quae et natus ducimus. Adipisci delectus quisquam aspernatur temporibus a dolorem iure aut explicabo laborum! Ab minus deleniti recusandae eos temporibus. Aspernatur minima eaque maxime molestiae laborum hic, quasi quos atque magnam facilis? Totam nam soluta labore illo voluptas similique dolorem optio ea exercitationem praesentium deserunt, omnis rem animi dignissimos ut reiciendis et! Alias repellendus sunt, velit, expedita hic magnam cupiditate, minima facilis impedit similique ipsum fugit dolorum maxime perferendis molestias obcaecati quis officiis. Iste, necessitatibus deserunt blanditiis consequatur mollitia aliquid ratione nobis eaque porro est totam illum vero voluptatem autem impedit amet ab iusto minus expedita quos. Amet a esse tempore nisi modi quisquam eos qui ullam in id ab quidem minus voluptatibus placeat ipsum nostrum vel atque asperiores recusandae reiciendis eligendi, autem dolore iusto molestias. Consequuntur, quaerat! Quam eveniet, nulla perferendis fuga est mollitia quis provident cumque officiis fugit quas hic quos eaque repellat magnam facere sed eligendi nisi dolorem laboriosam ab qui veritatis aut! Nesciunt voluptatem commodi quibusdam unde deleniti, itaque velit, voluptates quasi nostrum odit quos sit, maiores alias nulla tempore consequuntur. Ipsam corporis libero, odit in reprehenderit distinctio perspiciatis architecto, fugiat, debitis voluptatem impedit.</p>
        //     <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur similique, adipisci repellat vitae aliquam libero atque soluta iste qui perspiciatis magnam earum ratione alias sed voluptatibus ad animi sint fugiat consequuntur iusto eos eaque quae. Nihil neque, recusandae magnam ut ratione quia voluptate. Deleniti, error numquam. Sed, alias. Sunt hic magnam, delectus vero placeat voluptas quidem culpa mollitia suscipit quis odit ullam, reprehenderit harum labore! Maiores nihil dolorem iusto, doloribus, voluptatum nostrum eum ratione asperiores molestiae minus minima perspiciatis natus. Reprehenderit consequuntur officiis quas voluptate voluptatibus? Sunt unde vel dolorum dolor commodi eveniet! Dolorum exercitationem eligendi odit earum, cumque, voluptatibus magni repudiandae quidem ab ad velit, doloribus saepe ex deserunt assumenda vitae dolores eaque illo quasi tenetur porro veniam temporibus! Ea nostrum, nobis cupiditate, quam sunt ullam quod facere nisi magni porro autem eum nam? Illo magni quia recusandae numquam quasi amet ea, cum asperiores voluptatem repellendus libero, blanditiis quis! Provident iusto accusamus quo fugit nisi, corrupti suscipit omnis, assumenda consequatur magnam ipsum odio obcaecati soluta corporis laborum mollitia quod vel libero asperiores deleniti autem voluptas doloremque beatae numquam. Voluptates facere dolor iste quo ipsam. Temporibus ad, iure, nulla cumque repudiandae sed magni iusto porro consequatur eveniet saepe quod dolorem culpa dolorum corporis ratione voluptatibus reprehenderit ea obcaecati consectetur deleniti enim sunt hic laborum! Eos architecto quia ut beatae nostrum totam, porro soluta ipsum omnis amet assumenda alias aspernatur. Aut eos ullam velit! Rem repellendus labore praesentium itaque incidunt eum repellat sit. Obcaecati ea recusandae blanditiis porro harum ipsa? Corporis recusandae repellendus repudiandae quaerat saepe obcaecati error aut, animi assumenda, in eius. Aliquid quam praesentium a inventore alias quod vel dicta nam officiis, enim quos accusamus hic harum accusantium deleniti, ab veniam ea dolore obcaecati aut odio eius. Harum, corrupti tempore! Atque, voluptatibus suscipit aut ut quisquam dignissimos ad vitae!</p>',
        //     'user_id' => 1,
        // ]);



        Mading::factory(10)->create();

        User::create([
            'name' => 'Guru-01',
            'username' => 'Guru-01',
            'email' => 'guru1@gmail.com',
            'role' => 'GURU',
            'number' => '089977536523',
            'password' => bcrypt('guru123')
        ]);

        User::create([
            'name' => 'Admin Mading',
            'username' => 'admin-01',
            'email' => 'admin@gmail.com',
            'role' => 'ADMIN',
            'number' => '085861235561',
            'password' => bcrypt('admin123')
        ]);

        User::create([
            'name' => 'Murid-01',
            'username' => 'Murid-01',
            'email' => 'murid1@gmail.com',
            'kelas' => 'XI RPL',
            'number' => '081224242608',
            'password' => bcrypt('murid123')
        ]);

    }
}
